filename=`date +%Y_%m_%d`
mkdir ./${filename}
cd ./${filename}
mkdir ./boxes
mkdir ./frustum_cloud
mkdir ./surface_cloud
mkdir ./vehicle_cloud
a=0
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./frustum_cloud/$a
mkdir ./surface_cloud/$a
mkdir ./vehicle_cloud/$a
cd ..

