filename=`date +%Y_%m_%d`
mkdir ./${filename}
cd ./${filename}
mkdir ./boxes
mkdir ./point_cloud
a=0
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
let a++
mkdir ./boxes/$a
mkdir ./point_cloud/$a
cd ..

